### PR TITLE
Update RiotSharp and contact page

### PR DESCRIPTION
**Pull request by jvanvugt**

### CODE REVIEW

**Comment by StevenReitsma** [comment]
Some changes were applied to RiotSharp to enable mocking. Did you check whether those changes are still needed? They are in fcda2b0ba6ea39bd7c9019915aa47be08ef62d8d.

Rest: looks good. I'll push my own commits this afternoon and will merge if there are no conflicts.

**Comment by jvanvugt** [comment]
I have reverted the changes to the Tier enum. The changes made in fcda2b0 are still necessary, because classes can't be instantiated without a visible constructor.

**Comment by StevenReitsma** [comment]
What I actually meant was whether you checked whether those classes are still public instead of internal. I just checked it myself and it seems there were no changes to those classes, so it's all good. Will merge this afternoon/evening.

**Comment by StevenReitsma** [comment]
Looks like there are some conflicts. Do you want to fix them or would you rather have me take a look at it?

**Comment by jvanvugt** [comment]
I can't see the conflicts, because I don't have write access. I'll take a look at them tonight probably if I can see them.

**Comment by StevenReitsma** [comment]
You can merge the current master in your branch to fix the conflicts. You don't need write access.

**Pull request merged**
